use beatkernel::{
    input::*,
    replay::{codec::*, *},
    time::*,
};
use beatkernel_bms_runtime::{
    local_players::PlayerId,
    multiplayer_group::{GroupPrefix, MemberProgress},
    multiplayer_group_rooms::{GroupRoomMember, GroupRoomPhase},
    multiplayer_protocol::Progress,
    multiplayer_room_wire::{decode_message, encode_message, RoomMessage},
    multiplayer_rooms::ParticipantId,
    multiplayer_start::StartMessage,
};
use beatkernel_layer_fuzz::codecs::*;

fn meta() -> EventMeta {
    EventMeta {
        source: DeviceId(u64::MAX),
        timestamp: Timestamp::MIN,
        clock_domain: ClockDomainId(3),
        sequence: u64::MAX,
        native: Some(NativeEventMeta {
            backend: BackendId(u32::MAX),
            code: Some(0),
            timestamp: Some(ClockPoint {
                domain: ClockDomainId(77),
                timestamp: Timestamp::MAX,
            }),
        }),
        original_clock_point: Some(ClockPoint {
            domain: ClockDomainId(91),
            timestamp: Timestamp::from_nanos(-99),
        }),
    }
}

fn physical_cases() -> Vec<PhysicalInputEvent> {
    let meta = meta();
    let control = PhysicalControlId::Vendor {
        namespace: VendorNamespaceId(33),
        code: 44,
    };
    let mut cases = vec![];
    for state in [ButtonState::Down, ButtonState::Up, ButtonState::Repeat] {
        cases.push(PhysicalInputEvent::Button(ButtonEvent {
            meta,
            control,
            state,
        }));
    }
    // Both NaN signs/payloads, signaling NaNs, zero signs, infinities and subnormal.
    for bits in [
        0,
        0x8000_0000,
        0x7fc1_2345,
        0xffc5_4321,
        0x7fa1_2345,
        0xffa0_0001,
        1,
        0x7f80_0000,
        0xff80_0000,
    ] {
        for mode in [AxisMode::Absolute, AxisMode::Relative] {
            cases.push(PhysicalInputEvent::Axis(AxisEvent {
                meta,
                control,
                value: f32::from_bits(bits),
                mode,
            }));
        }
    }
    for phase in [
        TouchPhase::Down,
        TouchPhase::Move,
        TouchPhase::Up,
        TouchPhase::Cancel,
    ] {
        for pressure in [None, Some(f32::from_bits(0x7fa1_2345)), Some(-0.0)] {
            cases.push(PhysicalInputEvent::Touch(TouchEvent {
                meta,
                control,
                contact: ContactId(u64::MAX),
                phase,
                position: Position2 {
                    x: f32::from_bits(0xffc5_4321),
                    y: 0.0,
                },
                pressure,
            }));
        }
    }
    for mode in [PointerMode::Absolute, PointerMode::Relative] {
        cases.push(PhysicalInputEvent::Pointer(PointerEvent {
            meta,
            control,
            mode,
            position: Position2 {
                x: -0.0,
                y: f32::from_bits(0x7fa1_2345),
            },
        }));
    }
    cases.push(PhysicalInputEvent::Pose(PoseEvent {
        meta,
        control,
        position: Position3 {
            x: 0.0,
            y: -0.0,
            z: f32::from_bits(1),
        },
        orientation: Quaternion {
            x: f32::from_bits(0x7fc1_2345),
            y: f32::from_bits(0xffa0_0001),
            z: f32::INFINITY,
            w: f32::NEG_INFINITY,
        },
    }));
    for report_id in [None, Some(0), Some(255)] {
        cases.push(PhysicalInputEvent::RawHidReport(RawHidReportEvent {
            meta,
            report_id,
            data: vec![0, 255, 17],
        }));
    }
    cases.push(PhysicalInputEvent::Custom(CustomInputEvent {
        meta,
        namespace: VendorNamespaceId(u32::MAX),
        type_id: u32::MAX,
        payload: vec![255, 0, 128],
    }));
    cases
}

// Compare fields directly against the constructed event, never float PartialEq
// or bytes generated by the same encoder as their own correctness oracle.
fn assert_physical(expected: &PhysicalInputEvent, actual: &PhysicalInputEvent) {
    assert_eq!(actual.meta(), expected.meta());
    match (expected, actual) {
        (PhysicalInputEvent::Axis(a), PhysicalInputEvent::Axis(b)) => {
            assert_eq!(b.control, a.control);
            assert_eq!(b.mode, a.mode);
            assert_eq!(b.value.to_bits(), a.value.to_bits());
        }
        (PhysicalInputEvent::Touch(a), PhysicalInputEvent::Touch(b)) => {
            assert_eq!(
                (b.control, b.contact, b.phase),
                (a.control, a.contact, a.phase)
            );
            assert_eq!(
                (b.position.x.to_bits(), b.position.y.to_bits()),
                (a.position.x.to_bits(), a.position.y.to_bits())
            );
            assert_eq!(b.pressure.map(f32::to_bits), a.pressure.map(f32::to_bits));
        }
        (PhysicalInputEvent::Pointer(a), PhysicalInputEvent::Pointer(b)) => {
            assert_eq!((b.control, b.mode), (a.control, a.mode));
            assert_eq!(
                (b.position.x.to_bits(), b.position.y.to_bits()),
                (a.position.x.to_bits(), a.position.y.to_bits())
            );
        }
        (PhysicalInputEvent::Pose(a), PhysicalInputEvent::Pose(b)) => {
            assert_eq!(b.control, a.control);
            assert_eq!(
                [
                    b.position.x.to_bits(),
                    b.position.y.to_bits(),
                    b.position.z.to_bits(),
                    b.orientation.x.to_bits(),
                    b.orientation.y.to_bits(),
                    b.orientation.z.to_bits(),
                    b.orientation.w.to_bits()
                ],
                [
                    a.position.x.to_bits(),
                    a.position.y.to_bits(),
                    a.position.z.to_bits(),
                    a.orientation.x.to_bits(),
                    a.orientation.y.to_bits(),
                    a.orientation.z.to_bits(),
                    a.orientation.w.to_bits()
                ]
            );
        }
        (PhysicalInputEvent::Button(a), PhysicalInputEvent::Button(b)) => assert_eq!(b, a),
        (PhysicalInputEvent::RawHidReport(a), PhysicalInputEvent::RawHidReport(b)) => {
            assert_eq!(b, a)
        }
        (PhysicalInputEvent::Custom(a), PhysicalInputEvent::Custom(b)) => assert_eq!(b, a),
        _ => panic!("physical variant changed"),
    }
}

fn replay(events: Vec<PhysicalInputEvent>) -> ReplayFile {
    let mut records: Vec<_> = events
        .into_iter()
        .enumerate()
        .map(|(index, physical)| ReplayRecord {
            ordinal: index as u64,
            song_time: Timestamp::from_nanos(index as i64),
            operation: ReplayOperation::Input(GameInputEvent {
                game_control: GameControlId(u32::MAX),
                physical,
            }),
        })
        .collect();
    records.push(ReplayRecord {
        ordinal: records.len() as u64,
        song_time: Timestamp::MAX,
        operation: ReplayOperation::Advance,
    });
    let mut file = ReplayFile::new(
        ReplayHeader {
            version: REPLAY_VERSION,
            chart_identity: vec![0, 255, 17],
            rules_identity: vec![128, 0],
            options: vec![0, 255],
            seed: u64::MAX,
            normalized_clock: ClockDomainId(3),
        },
        records,
    );
    file.runtime_version = "independent-fixture/v1".into();
    file.calibration_metadata = Some(vec![255, 0, 17]);
    file
}

fn roomy_replay_limits() -> ReplayCodecLimits {
    ReplayCodecLimits::new(
        1_000_000,
        256,
        100_000,
        CodecLimits::new(100_000, 10_000).unwrap(),
    )
    .unwrap()
}

#[test]
fn frozen_campaign_limits_are_exact_and_nested() {
    assert_eq!((INPUT_MAX_BYTES, INPUT_MAX_PAYLOAD), (65_536, 4096));
    assert_eq!(
        (REPLAY_MAX_BYTES, REPLAY_MAX_RECORDS, REPLAY_MAX_HEADER),
        (65_536, 64, 4096)
    );
    assert_eq!(ROOM_MAX_BYTES, 131_072);
    assert_eq!(input_limits().max_encoded_bytes(), 65_536);
    assert_eq!(input_limits().max_payload_bytes(), 4096);
    assert_eq!(replay_limits().max_file_bytes(), 65_536);
    assert_eq!(replay_limits().max_records(), 64);
    assert_eq!(replay_limits().max_header_bytes(), 4096);
    assert_eq!(replay_limits().input_limits(), input_limits());
}

#[test]
fn input_all_variants_preserve_known_bits_and_native_provenance() {
    for event in physical_cases() {
        let bytes = encode_event(&event, input_limits()).unwrap();
        assert!(check_input(&bytes));
        let decoded = decode_event(&bytes, input_limits()).unwrap();
        assert_physical(&event, &decoded);
        let canonical = encode_event(&decoded, input_limits()).unwrap();
        let again = decode_event(&canonical, input_limits()).unwrap();
        assert_physical(&event, &again);
        assert_eq!(encode_event(&again, input_limits()).unwrap(), canonical);
    }
}

#[test]
fn independent_literal_axis_bits_are_accepted() {
    // BKPI v1, axis tag 1, device 1, time -1, clock 3, sequence 2,
    // absent provenance, keyboard HID usage 4, relative mode.
    let prefix = [
        66, 75, 80, 73, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 3,
        0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 4, 0,
    ];
    for bits in [0u32, 0x8000_0000, 0x7fc1_2345, 0x7fa1_2345, 0xffa0_0001] {
        let mut literal = prefix.to_vec();
        literal.extend_from_slice(&bits.to_le_bytes());
        literal.push(1);
        assert!(check_input(&literal));
        let PhysicalInputEvent::Axis(axis) = decode_event(&literal, input_limits()).unwrap() else {
            panic!("axis lost")
        };
        assert_eq!(axis.value.to_bits(), bits);
        assert_eq!(axis.meta.source, DeviceId(1));
        assert_eq!(axis.meta.timestamp, Timestamp::from_nanos(-1));
        assert_eq!(axis.mode, AxisMode::Relative);
    }
}

#[test]
fn input_metadata_option_combinations_remain_distinct() {
    for native in [false, true] {
        for code in [None, Some(0), Some(u32::MAX)] {
            for point in [
                None,
                Some(ClockPoint {
                    domain: ClockDomainId(77),
                    timestamp: Timestamp::MAX,
                }),
            ] {
                for origin in [None, meta().original_clock_point] {
                    let mut expected = meta();
                    expected.native = native.then_some(NativeEventMeta {
                        backend: BackendId(9),
                        code,
                        timestamp: point,
                    });
                    expected.original_clock_point = origin;
                    let event = PhysicalInputEvent::Button(ButtonEvent {
                        meta: expected,
                        control: PhysicalControlId::keyboard(4),
                        state: ButtonState::Repeat,
                    });
                    let bytes = encode_event(&event, input_limits()).unwrap();
                    assert!(check_input(&bytes));
                    assert_eq!(
                        decode_event(&bytes, input_limits()).unwrap().meta(),
                        &expected
                    );
                }
            }
        }
    }
}

#[test]
fn input_rejects_truncation_trailing_tags_and_oversized_payloads() {
    for event in physical_cases() {
        let bytes = encode_event(&event, input_limits()).unwrap();
        for cut in 0..bytes.len() {
            assert!(!check_input(&bytes[..cut]));
        }
        let mut trailing = bytes.clone();
        trailing.push(0);
        assert!(!check_input(&trailing));
        for offset in [0, 4, 6] {
            let mut invalid = bytes.clone();
            invalid[offset] = 255;
            assert!(decode_event(&invalid, input_limits()).is_err());
            assert!(!check_input(&invalid));
        }
    }
    for size in [4096, 4097] {
        for event in [
            PhysicalInputEvent::RawHidReport(RawHidReportEvent {
                meta: meta(),
                report_id: None,
                data: vec![17; size],
            }),
            PhysicalInputEvent::Custom(CustomInputEvent {
                meta: meta(),
                namespace: VendorNamespaceId(1),
                type_id: 2,
                payload: vec![17; size],
            }),
        ] {
            let bytes = encode_event(&event, CodecLimits::new(100_000, 10_000).unwrap()).unwrap();
            assert_eq!(check_input(&bytes), size == 4096);
            assert_eq!(decode_event(&bytes, input_limits()).is_ok(), size == 4096);
        }
    }
    assert!(!check_input(&vec![0; 65_537]));
}

#[test]
fn replay_embedded_inputs_preserve_raw_bits_and_original_metadata() {
    let expected = replay(physical_cases());
    let bytes = encode_replay(&expected, replay_limits()).unwrap();
    assert!(check_replay(&bytes));
    let actual = decode_replay(&bytes, replay_limits()).unwrap();
    assert_eq!(actual.header, expected.header);
    assert_eq!(actual.runtime_version, "independent-fixture/v1");
    assert_eq!(actual.calibration_metadata, Some(vec![255, 0, 17]));
    assert_eq!(actual.records.len(), expected.records.len());
    for (a, b) in expected.records.iter().zip(&actual.records) {
        assert_eq!((b.ordinal, b.song_time), (a.ordinal, a.song_time));
        match (&a.operation, &b.operation) {
            (ReplayOperation::Input(a), ReplayOperation::Input(b)) => {
                assert_eq!(b.game_control, GameControlId(u32::MAX));
                assert_physical(&a.physical, &b.physical);
            }
            (ReplayOperation::Advance, ReplayOperation::Advance) => {}
            _ => panic!("replay operation changed"),
        }
    }
    let canonical = encode_replay(&actual, replay_limits()).unwrap();
    assert_eq!(
        encode_replay(
            &decode_replay(&canonical, replay_limits()).unwrap(),
            replay_limits()
        )
        .unwrap(),
        canonical
    );
}

#[test]
fn replay_record_header_and_nested_payload_budgets_are_independent() {
    for count in [64, 65] {
        let mut file = replay(vec![]);
        file.records = (0..count)
            .map(|index| ReplayRecord {
                ordinal: index,
                song_time: Timestamp::from_nanos(index as i64),
                operation: ReplayOperation::Advance,
            })
            .collect();
        let bytes = encode_replay(&file, roomy_replay_limits()).unwrap();
        assert_eq!(decode_replay(&bytes, replay_limits()).is_ok(), count == 64);
        assert_eq!(check_replay(&bytes), count == 64);
    }
    for size in [4096, 4097] {
        let mut file = replay(vec![]);
        file.runtime_version.clear();
        file.header.chart_identity = vec![17; size];
        file.header.rules_identity.clear();
        file.header.options.clear();
        file.calibration_metadata = None;
        let bytes = encode_replay(&file, roomy_replay_limits()).unwrap();
        assert_eq!(check_replay(&bytes), size == 4096);
        assert_eq!(decode_replay(&bytes, replay_limits()).is_ok(), size == 4096);
        let file = replay(vec![PhysicalInputEvent::Custom(CustomInputEvent {
            meta: meta(),
            namespace: VendorNamespaceId(1),
            type_id: 2,
            payload: vec![17; size],
        })]);
        let bytes = encode_replay(&file, roomy_replay_limits()).unwrap();
        assert_eq!(check_replay(&bytes), size == 4096);
        assert_eq!(decode_replay(&bytes, replay_limits()).is_ok(), size == 4096);
    }
    assert!(!check_replay(&vec![0; 65_537]));
}

#[test]
fn replay_rejects_trailing_truncation_tags_and_invalid_chronology() {
    let file = replay(vec![]);
    let bytes = encode_replay(&file, replay_limits()).unwrap();
    assert!(check_replay(&bytes));
    for cut in 0..bytes.len() {
        assert!(!check_replay(&bytes[..cut]));
    }
    let mut trailing = bytes.clone();
    trailing.push(0);
    assert!(!check_replay(&trailing));
    for offset in [0, 8, bytes.len() - 1] {
        let mut invalid = bytes.clone();
        invalid[offset] = 255;
        assert!(decode_replay(&invalid, replay_limits()).is_err());
        assert!(!check_replay(&invalid));
    }
    let mut invalid = bytes;
    let ordinal = invalid.len() - 17;
    invalid[ordinal..ordinal + 8].copy_from_slice(&1u64.to_le_bytes());
    assert!(decode_replay(&invalid, replay_limits()).is_err());
    assert!(!check_replay(&invalid));
}

#[test]
fn hostile_declared_lengths_and_record_counts_are_normal_rejections() {
    let simple = EventMeta::new(
        DeviceId(1),
        ClockPoint {
            domain: ClockDomainId(3),
            timestamp: Timestamp::ZERO,
        },
        0,
    );
    let event = PhysicalInputEvent::RawHidReport(RawHidReportEvent {
        meta: simple,
        report_id: None,
        data: vec![17],
    });
    let bytes = encode_event(&event, input_limits()).unwrap();
    assert!(check_input(&bytes));
    // Header/event + base metadata + two absent metadata options + absent
    // report-id occupy 38 bytes; the next eight declare opaque payload size.
    for length in [4097u64, u64::MAX] {
        let mut invalid = bytes.clone();
        invalid[38..46].copy_from_slice(&length.to_le_bytes());
        assert!(decode_event(&invalid, input_limits()).is_err());
        assert!(!check_input(&invalid));
    }
    let bytes = encode_replay(&replay(vec![]), replay_limits()).unwrap();
    let count_offset = bytes.len() - 17 - 8; // single 17-byte Advance record
    for count in [65u64, u64::MAX] {
        let mut invalid = bytes.clone();
        invalid[count_offset..count_offset + 8].copy_from_slice(&count.to_le_bytes());
        assert!(decode_replay(&invalid, replay_limits()).is_err());
        assert!(!check_replay(&invalid));
    }
}

fn room_cases() -> Vec<RoomMessage> {
    let participant = ParticipantId(u64::MAX);
    let prefix = GroupPrefix {
        sequence: u64::MAX,
        final_prefix: true,
        members: vec![MemberProgress {
            player: PlayerId(u32::MAX),
            progress: Progress {
                song_ns: i64::MIN,
                hits: u64::MAX,
                misses: 0,
                combo: 17,
                max_combo: u64::MAX,
            },
        }],
    };
    let mut cases = vec![
        RoomMessage::Join {
            identity: vec![0, 255, 17],
            players: vec![PlayerId(1), PlayerId(u32::MAX)],
        },
        RoomMessage::Admitted { participant },
        RoomMessage::Snapshot {
            members: vec![GroupRoomMember {
                id: participant,
                players: vec![PlayerId(1)],
                prepared: false,
            }],
            phase: GroupRoomPhase::Collecting,
            deadline_ns: Some(i64::MAX),
        },
        RoomMessage::Seal,
        RoomMessage::Ready,
        RoomMessage::Leave,
        RoomMessage::ClockPing {
            sequence: u64::MAX,
            sent_ns: 0,
        },
        RoomMessage::ClockPong {
            sequence: u64::MAX,
            sent_ns: 17,
            received_ns: 0,
            replied_ns: i64::MAX,
        },
        RoomMessage::Progress(prefix.clone()),
        RoomMessage::PeerProgress {
            participant,
            prefix,
        },
        RoomMessage::FinalAck {
            participant,
            sequence: u64::MAX,
        },
        RoomMessage::DrainReady {
            participant,
            sequence: u64::MAX,
        },
        RoomMessage::DrainComplete {
            participant,
            sequence: u64::MAX,
        },
    ];
    for message in [
        StartMessage::ClockReady(0),
        StartMessage::Propose(i64::MAX),
        StartMessage::Accept(17),
        StartMessage::Commit(17),
    ] {
        cases.push(RoomMessage::Start(message));
    }
    cases
}

#[test]
fn room_every_message_and_start_variant_is_accepted_with_owned_fields() {
    for expected in room_cases() {
        let mut bytes = encode_message(&expected).unwrap();
        assert!(check_room(&bytes));
        let decoded = decode_message(&bytes).unwrap();
        bytes.fill(0);
        assert_eq!(decoded, expected);
    }
}

#[test]
fn room_maximum_join_is_65808_bytes_and_inside_campaign() {
    let expected = RoomMessage::Join {
        identity: vec![17; 65_536],
        players: (1..=64).map(PlayerId).collect(),
    };
    let bytes = encode_message(&expected).unwrap();
    assert_eq!(bytes.len(), 65_808);
    assert_eq!(&bytes[..11], &[66, 75, 77, 82, 2, 0, 1, 5, 1, 1, 0]);
    assert_eq!(&bytes[11..15], &65_536u32.to_le_bytes());
    assert_eq!(bytes[65_551], 64);
    assert!(check_room(&bytes));
    assert_eq!(decode_message(&bytes).unwrap(), expected);
}

#[test]
fn room_independent_literals_and_malformed_frames_classify_correctly() {
    for tag in [4, 5, 6] {
        let literal = [66, 75, 77, 82, 2, 0, tag, 0, 0, 0, 0];
        let expected = match tag {
            4 => RoomMessage::Seal,
            5 => RoomMessage::Ready,
            _ => RoomMessage::Leave,
        };
        assert_eq!(decode_message(&literal).unwrap(), expected);
        assert!(check_room(&literal));
    }
    for message in room_cases() {
        let bytes = encode_message(&message).unwrap();
        for cut in 0..bytes.len() {
            assert!(!check_room(&bytes[..cut]));
        }
        let mut trailing = bytes.clone();
        trailing.push(0);
        assert!(!check_room(&trailing));
        for offset in [0, 4, 6] {
            let mut invalid = bytes.clone();
            invalid[offset] = 255;
            assert!(decode_message(&invalid).is_err());
            assert!(!check_room(&invalid));
        }
        let mut invalid_extent = bytes;
        invalid_extent[7..11].copy_from_slice(&u32::MAX.to_le_bytes());
        assert!(decode_message(&invalid_extent).is_err());
        assert!(!check_room(&invalid_extent));
    }
    assert!(!check_room(&vec![0; 131_073]));
}

#[test]
fn room_syntactically_complete_invalid_values_are_refused() {
    // Valid extents alone do not make participant zero or negative clock time valid.
    for (tag, payload) in [
        (2, vec![0; 8]),
        (7, [1u64.to_le_bytes(), (-1i64).to_le_bytes()].concat()),
        (9, (-1i64).to_le_bytes().to_vec()),
        (15, [1u64.to_le_bytes(), 0u64.to_le_bytes()].concat()),
    ] {
        let mut frame = vec![66, 75, 77, 82, 2, 0, tag];
        frame.extend_from_slice(&(payload.len() as u32).to_le_bytes());
        frame.extend_from_slice(&payload);
        assert!(decode_message(&frame).is_err());
        assert!(!check_room(&frame));
    }
    let valid = encode_message(&RoomMessage::Join {
        identity: vec![17],
        players: vec![PlayerId(1)],
    })
    .unwrap();
    assert!(check_room(&valid));
    let mut zero_player = valid.clone();
    zero_player[17..21].fill(0);
    assert!(decode_message(&zero_player).is_err());
    assert!(!check_room(&zero_player));
    let mut zero_count = valid;
    zero_count[16] = 0;
    assert!(decode_message(&zero_count).is_err());
    assert!(!check_room(&zero_count));
}
